### ISSUE TITLE
Decoded params

### ISSUE THREAD

**Issue by 89z** [mansuf/youtube-search-requests#1]
I see you have some filters here:

https://github.com/mansuf/youtube-search-requests/blob/63c70ece7be4590c4e31df2c510d646e30744f2c/youtube_search_requests/constants.py#L18-L39

If youre interested, I found out that those are actually Protobuf encoded values. I have the decoded values here if it helps:

https://github.com/89z/mech/blob/master/youtube/proto.go

**Comment by mansuf** [comment]
I appreciate you give the decoded values for me. But it seems protobuf require a "compiler" which users have to install it.

I will stay for the encoded values since users don't have to install "protobuf compiler" while installing youtube-search-requests.

**Comment by mansuf** [comment]
Btw, i wonder how did you get all of those things ?

**Comment by 89z** [comment]
You don't need a compiler, you can do but with pure python

https://github.com/user234683/youtube-local/blob/master/youtube/proto.py

The strings are base64 encoded. After I decoded them, I used this to unmarshal

https://godocs.io/google.golang.org/protobuf/testing/protopack#Message.UnmarshalAbductive

**Comment by mansuf** [comment]
i don't understand about these protobuf things. All i know is just grabbing encoded values and put in to `constants.py`. Simple as that.

Is there are any different using encoded protobuf values and the decoded one ?. I have read the documentation but still its confusing...

**Comment by 89z** [comment]
Well, if you use the decoded values, you can combine filters, for example HD and TODAY, without having to hardcode the hundreds of possible combinations

**Comment by mansuf** [comment]
Hmmm, sounds interesting. Maybe i will implement it soon after i rework the base code (because it really messed up). Thanks for the information by the way 😄 .

**Comment by 89z** [comment]
Closing this in favor of my own package:

https://github.com/89z/mech/blob/v1.37.1/youtube/proto.go
